# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Copy source code
COPY src ./src

# Install dependencies and build
RUN npm ci --ignore-scripts && npm run build

# Runtime stage
FROM node:lts-alpine
WORKDIR /app
ENV NODE_ENV=production

# Copy build artifacts
COPY --from=builder /app/build ./build

# Copy production dependencies
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts

# Entrypoint for MCP
ENTRYPOINT ["node", "build/index.js"]
